# Generated by Django 4.2.15 on 2024-10-11 09:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Health_Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heart_rate', models.FloatField()),
                ('blood_pressure', models.CharField(max_length=20)),
                ('spo2', models.FloatField()),
                ('breathing_rate', models.FloatField()),
                ('pro', models.FloatField()),
                ('hrv', models.FloatField()),
                ('stress', models.FloatField()),
                ('sympathetic_ns', models.FloatField()),
                ('parasympathetic_ns', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
