# Generated by Django 4.2.15 on 2024-10-15 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_app', '0002_alter_customuser_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='health_report',
            name='prq',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
