# Generated by Django 4.2.15 on 2024-10-12 14:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_app', '0002_health_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='health_report',
            name='current_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='health_report',
            name='breathing_rate',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='health_report',
            name='heart_rate',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='health_report',
            name='hrv',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='health_report',
            name='parasympathetic_ns',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='health_report',
            name='pro',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='health_report',
            name='spo2',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='health_report',
            name='stress',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='health_report',
            name='sympathetic_ns',
            field=models.CharField(max_length=20),
        ),
    ]
