# Generated by Django 4.2.15 on 2024-10-12 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_app', '0003_health_report_current_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='health_report',
            name='current_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
