# Generated by Django 4.2.15 on 2024-10-12 14:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_app', '0004_alter_health_report_current_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='health_report',
            name='current_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
